default_language_version:

  python: python3.11

repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.3.0
  hooks:
  - id: check-yaml

  - id: end-of-file-fixer
  - id: trailing-whitespace
  - id: check-ast
  - id: check-json
  - id: check-toml
  - id: check-yaml
  - id: pretty-format-json
    args: [--autofix, --no-sort-keys]
- repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
  rev: v2.13.0
  hooks:

  - id: pretty-format-toml
    args: [--autofix, --no-sort]
  - id: pretty-format-yaml

    args: [--autofix, --indent, '2', --line-width, '88']
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.1.11
  hooks:
  - id: ruff
    args: [--fix]

  - id: ruff-format
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v1.7.1
  hooks:
  - id: mypy
    additional_dependencies: [pydantic==2.9.2, pydantic_core==2.23.4, json_repair==0.29.2,
      langchain_core==0.3.5, langgraph==0.2.23, pytest==8.2.0]
    args: []
